/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dns Servers
         * @description Retrieve a list of available DNS servers.
         */
        get: operations["list_dns_servers_dns_servers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/lookup/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dns Lookup
         * @description Perform a DNS lookup for a given domain against a specified record type and multiple DNS servers.
         */
        get: operations["dns_lookup_dns_lookup__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/lookup/by-location/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deep Dns Lookup
         * @description Perform a DNS lookup for a given domain against a single DNS server, resolving all record types and following CNAME chains as necessary.
         */
        get: operations["deep_dns_lookup_dns_lookup_by_location__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DnsLookupResponse */
        DnsLookupResponse: {
            /** Records */
            records: components["schemas"]["SingleDnsLookupResponse"][];
        };
        /**
         * DnsLookupType
         * @enum {string}
         */
        DnsLookupType: "A" | "AAAA" | "CNAME" | "MX" | "NS" | "TXT";
        /** DnsMultipleRecordsLookupResponse */
        DnsMultipleRecordsLookupResponse: {
            /** Domain */
            domain: string;
            /** Records */
            records: components["schemas"]["SingleDnsLookupResponse"][];
            server: components["schemas"]["DnsServer"];
        };
        /**
         * DnsServer
         * @example {
         *       "city": "San Francisco",
         *       "country": "USA",
         *       "ips": [
         *         "1.1.1.1",
         *         "1.0.0.1"
         *       ],
         *       "location": {
         *         "coordinates": [
         *           -122.4194,
         *           37.7749
         *         ],
         *         "type": "Point"
         *       },
         *       "name": "Cloudflare DNS",
         *       "reliability": 99.9,
         *       "reputation": 98.5
         *     }
         */
        DnsServer: {
            /** Name */
            name: string;
            /** Ips */
            ips: string[];
            location: components["schemas"]["GeoPoint"];
            /** Reputation */
            reputation: number | null;
            /** Reliability */
            reliability: number | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
        };
        /** GeoPoint */
        GeoPoint: {
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
            /** Coordinates */
            coordinates: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RootResponseModel */
        RootResponseModel: {
            /** Message */
            message: string;
        };
        /**
         * SingleDnsLookupResponse
         * @example {
         *       "domain": "example.com",
         *       "record_type": "A",
         *       "records": [
         *         "1.1.1.1",
         *         "1.0.0.1"
         *       ],
         *       "server": {
         *         "ips": [
         *           "1.1.1.1",
         *           "1.0.0.1"
         *         ],
         *         "location": {
         *           "coordinates": [
         *             -122.0839,
         *             37.3861
         *           ],
         *           "type": "Point"
         *         },
         *         "name": "example.com",
         *         "reliability": 0.8,
         *         "reputation": 0.9
         *       }
         *     }
         */
        SingleDnsLookupResponse: {
            /** Domain */
            domain: string;
            /** Record Type */
            record_type: string;
            /** Records */
            records: string[] | null;
            server?: components["schemas"]["DnsServer"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponseModel"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponseModel"];
                };
            };
        };
    };
    list_dns_servers_dns_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsServer"][];
                };
            };
        };
    };
    dns_lookup_dns_lookup__domain__get: {
        parameters: {
            query?: {
                type?: components["schemas"]["DnsLookupType"];
            };
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deep_dns_lookup_dns_lookup_by_location__domain__get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                radius: number;
            };
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsMultipleRecordsLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
