[project]
name = "dns-api"
version = "0.1.0"
requires-python = "~=3.14.3"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "beanie",
    "pymongo",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "sentry-sdk",
    "httpx",
    "dns-models",
    "dnspython",
]

[dependency-groups]
dev = [
    "pytest>=8",
    "pytest-asyncio>=0.24",
    "pytest-mock>=3.14",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
pythonpath = ["../.."]

[tool.uv.sources]
dns-models = { workspace = true }
